DROP TABLE IF EXISTS LINGUAGEM_SISTEMA;

CREATE TABLE LINGUAGEM_SISTEMA(
    CODIGO_SISTEMA INTEGER NOT NULL REFERENCES SISTEMA_WEB(CODIGO) ON DELETE CASCADE,
    LINGUAGEM VARCHAR(50) NOT NULL,
    CONSTRAINT linguagem_sistema_pk PRIMARY KEY (CODIGO_SISTEMA, LINGUAGEM)
)
