DROP TABLE IF EXISTS SERVIDOR;

CREATE TABLE SERVIDOR(
    CODIGO SERIAL NOT NULL PRIMARY KEY,
    CAPACIDADE_PROCESSAMENTO INTEGER,
    QUANTIDADE_MEMORIA INTEGER,
    MODELO VARCHAR(40) NOT NULL,
    CODIGO_SO INTEGER NOT NULL REFERENCES SISTEMA_OPERACIONAL(CODIGO),
    CODIGO_PAIS INTEGER NOT NULL REFERENCES PAIS(CODIGO)
)
