DROP TABLE IF EXISTS HOSPEDA;

CREATE TABLE HOSPEDA(
    CODIGO SERIAL NOT NULL PRIMARY KEY,
    DATA_IMPLANTACAO DATE,
    CODIGO_SERVIDOR INTEGER REFERENCES SERVIDOR(CODIGO) ON DELETE CASCADE,
    CODIGO_SISTEMA INTEGER REFERENCES SISTEMA_WEB(CODIGO) ON DELETE CASCADE
)
