DROP TABLE IF EXISTS USUARIO;

CREATE TABLE USUARIO(
    EMAIL VARCHAR(100) NOT NULL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    CODIGO_PAIS INTEGER NOT NULL REFERENCES PAIS(CODIGO)
)
