DROP TABLE IF EXISTS LINGUAGEM_SISTEMA;

CREATE TABLE LINGUAGEM_SISTEMA(
    CODIGO_SISTEMA INTEGER NOT NULL PRIMARY KEY REFERENCES SISTEMA_WEB(CODIGO) ON DELETE CASCADE,
    LINGUAGEM VARCHAR(50) NOT NULL
)
