DROP TABLE IF EXISTS ACESSA;

CREATE TABLE ACESSA(
    ID INTEGER NOT NULL PRIMARY KEY,
    IP VARCHAR(16) NOT NULL,
    STATUS_HTTP INTEGER NOT NULL,
    LATENCIA INTEGER,
    TIMESTAMP_ACESSO TIMESTAMP NOT NULL,
    EMAIL_USUARIO VARCHAR(100) NOT NULL REFERENCES USUARIO(EMAIL) ON DELETE CASCADE,
    URL_PAGINA VARCHAR(512) NOT NULL REFERENCES PAGINA(_URL) ON DELETE CASCADE
)
